package errors

var errnos = []info{
	info{id: 1, name: "EPERM", doc: "Operation not permitted"},
	info{id: 2, name: "ENOENT", doc: "No such file or directory"},
	info{id: 3, name: "ESRCH", doc: "No such process"},
	info{id: 4, name: "EINTR", doc: "Interrupted system call"},
	info{id: 5, name: "EIO", doc: "I/O error"},
	info{id: 6, name: "ENXIO", doc: "No such device or address"},
	info{id: 7, name: "E2BIG", doc: "Arg list too long"},
	info{id: 8, name: "ENOEXEC", doc: "Exec format error"},
	info{id: 9, name: "EBADF", doc: "Bad file number"},
	info{id: 10, name: "ECHILD", doc: "No child processes"},
	info{id: 11, name: "EAGAIN", doc: "Try again"},
	info{id: 12, name: "ENOMEM", doc: "Out of memory"},
	info{id: 13, name: "EACCES", doc: "Permission denied"},
	info{id: 14, name: "EFAULT", doc: "Bad address"},
	info{id: 15, name: "ENOTBLK", doc: "Block device required"},
	info{id: 16, name: "EBUSY", doc: "Device or resource busy"},
	info{id: 17, name: "EEXIST", doc: "File exists"},
	info{id: 18, name: "EXDEV", doc: "Cross-device link"},
	info{id: 19, name: "ENODEV", doc: "No such device"},
	info{id: 20, name: "ENOTDIR", doc: "Not a directory"},
	info{id: 21, name: "EISDIR", doc: "Is a directory"},
	info{id: 22, name: "EINVAL", doc: "Invalid argument"},
	info{id: 23, name: "ENFILE", doc: "File table overflow"},
	info{id: 24, name: "EMFILE", doc: "Too many open files"},
	info{id: 25, name: "ENOTTY", doc: "Not a typewriter"},
	info{id: 26, name: "ETXTBSY", doc: "Text file busy"},
	info{id: 27, name: "EFBIG", doc: "File too large"},
	info{id: 28, name: "ENOSPC", doc: "No space left on device"},
	info{id: 29, name: "ESPIPE", doc: "Illegal seek"},
	info{id: 30, name: "EROFS", doc: "Read-only file system"},
	info{id: 31, name: "EMLINK", doc: "Too many links"},
	info{id: 32, name: "EPIPE", doc: "Broken pipe"},
	info{id: 33, name: "EDOM", doc: "Math argument out of domain of func"},
	info{id: 34, name: "ERANGE", doc: "Math result not representable"},
	info{id: 35, name: "EDEADLK", doc: "Resource deadlock would occur"},
	info{id: 36, name: "ENAMETOOLONG", doc: "File name too long"},
	info{id: 37, name: "ENOLCK", doc: "No record locks available"},
	info{id: 38, name: "ENOSYS", doc: "Function not implemented"},
	info{id: 39, name: "ENOTEMPTY", doc: "Directory not empty"},
	info{id: 40, name: "ELOOP", doc: "Too many symbolic links encountered"},
	info{id: 41, name: "EWOULDBLOCK", doc: "Operation would block"},
	info{id: 42, name: "ENOMSG", doc: "No message of desired type"},
	info{id: 43, name: "EIDRM", doc: "Identifier removed"},
	info{id: 44, name: "ECHRNG", doc: "Channel number out of range"},
	info{id: 45, name: "EL2NSYNC", doc: "Level 2 not synchronized"},
	info{id: 46, name: "EL3HLT", doc: "Level 3 halted"},
	info{id: 47, name: "EL3RST", doc: "Level 3 reset"},
	info{id: 48, name: "ELNRNG", doc: "Link number out of range"},
	info{id: 49, name: "EUNATCH", doc: "Protocol driver not attached"},
	info{id: 50, name: "ENOCSI", doc: "No CSI structure available"},
	info{id: 51, name: "EL2HLT", doc: "Level 2 halted"},
	info{id: 52, name: "EBADE", doc: "Invalid exchange"},
	info{id: 53, name: "EBADR", doc: "Invalid request descriptor"},
	info{id: 54, name: "EXFULL", doc: "Exchange full"},
	info{id: 55, name: "ENOANO", doc: "No anode"},
	info{id: 56, name: "EBADRQC", doc: "Invalid request code"},
	info{id: 57, name: "EBADSLT", doc: "Invalid slot"},
	info{id: 58, name: "EDEADLOCK", doc: "File locking deadlock error"},
	info{id: 59, name: "EBFONT", doc: "Bad font file format"},
	info{id: 60, name: "ENOSTR", doc: "Device not a stream"},
	info{id: 61, name: "ENODATA", doc: "No data available"},
	info{id: 62, name: "ETIME", doc: "Timer expired"},
	info{id: 63, name: "ENOSR", doc: "Out of streams resources"},
	info{id: 64, name: "ENONET", doc: "Machine is not on the network"},
	info{id: 65, name: "ENOPKG", doc: "Package not installed"},
	info{id: 66, name: "EREMOTE", doc: "Object is remote"},
	info{id: 67, name: "ENOLINK", doc: "Link has been severed"},
	info{id: 68, name: "EADV", doc: "Advertise error"},
	info{id: 69, name: "ESRMNT", doc: "Srmount error"},
	info{id: 70, name: "ECOMM", doc: "Communication error on send"},
	info{id: 71, name: "EPROTO", doc: "Protocol error"},
	info{id: 72, name: "EMULTIHOP", doc: "Multihop attempted"},
	info{id: 73, name: "EDOTDOT", doc: "RFS specific error"},
	info{id: 74, name: "EBADMSG", doc: "Not a data message"},
	info{id: 75, name: "EOVERFLOW", doc: "Value too large for defined data type"},
	info{id: 76, name: "ENOTUNIQ", doc: "Name not unique on network"},
	info{id: 77, name: "EBADFD", doc: "File descriptor in bad state"},
	info{id: 78, name: "EREMCHG", doc: "Remote address changed"},
	info{id: 79, name: "ELIBACC", doc: "Can not access a needed shared library"},
	info{id: 80, name: "ELIBBAD", doc: "Accessing a corrupted shared library"},
	info{id: 81, name: "ELIBSCN", doc: ".lib section in a.out corrupted"},
	info{id: 82, name: "ELIBMAX", doc: "Attempting to link in too many shared libraries"},
	info{id: 83, name: "ELIBEXEC", doc: "Cannot exec a shared library directly"},
	info{id: 84, name: "EILSEQ", doc: "Illegal byte sequence"},
	info{id: 85, name: "ERESTART", doc: "Interrupted system call should be restarted"},
	info{id: 86, name: "ESTRPIPE", doc: "Streams pipe error"},
	info{id: 87, name: "EUSERS", doc: "Too many users"},
	info{id: 88, name: "ENOTSOCK", doc: "Socket operation on non-socket"},
	info{id: 89, name: "EDESTADDRREQ", doc: "Destination address required"},
	info{id: 90, name: "EMSGSIZE", doc: "Message too long"},
	info{id: 91, name: "EPROTOTYPE", doc: "Protocol wrong type for socket"},
	info{id: 92, name: "ENOPROTOOPT", doc: "Protocol not available"},
	info{id: 93, name: "EPROTONOSUPPORT", doc: "Protocol not supported"},
	info{id: 94, name: "ESOCKTNOSUPPORT", doc: "Socket type not supported"},
	info{id: 95, name: "EOPNOTSUPP", doc: "Operation not supported on transport endpoint"},
	info{id: 96, name: "EPFNOSUPPORT", doc: "Protocol family not supported"},
	info{id: 97, name: "EAFNOSUPPORT", doc: "Address family not supported by protocol"},
	info{id: 98, name: "EADDRINUSE", doc: "Address already in use"},
	info{id: 99, name: "EADDRNOTAVAIL", doc: "Cannot assign requested address"},
	info{id: 100, name: "ENETDOWN", doc: "Network is down"},
	info{id: 101, name: "ENETUNREACH", doc: "Network is unreachable"},
	info{id: 102, name: "ENETRESET", doc: "Network dropped connection because of reset"},
	info{id: 103, name: "ECONNABORTED", doc: "Software caused connection abort"},
	info{id: 104, name: "ECONNRESET", doc: "Connection reset by peer"},
	info{id: 105, name: "ENOBUFS", doc: "No buffer space available"},
	info{id: 106, name: "EISCONN", doc: "Transport endpoint is already connected"},
	info{id: 107, name: "ENOTCONN", doc: "Transport endpoint is not connected"},
	info{id: 108, name: "ESHUTDOWN", doc: "Cannot send after transport endpoint shutdown"},
	info{id: 109, name: "ETOOMANYREFS", doc: "Too many references: cannot splice"},
	info{id: 110, name: "ETIMEDOUT", doc: "Connection timed out"},
	info{id: 111, name: "ECONNREFUSED", doc: "Connection refused"},
	info{id: 112, name: "EHOSTDOWN", doc: "Host is down"},
	info{id: 113, name: "EHOSTUNREACH", doc: "No route to host"},
	info{id: 114, name: "EALREADY", doc: "Operation already in progress"},
	info{id: 115, name: "EINPROGRESS", doc: "Operation now in progress"},
	info{id: 116, name: "ESTALE", doc: "Stale NFS file handle"},
	info{id: 117, name: "EUCLEAN", doc: "Structure needs cleaning"},
	info{id: 118, name: "ENOTNAM", doc: "Not a XENIX named type file"},
	info{id: 119, name: "ENAVAIL", doc: "No XENIX semaphores available"},
	info{id: 120, name: "EISNAM", doc: "Is a named type file"},
	info{id: 121, name: "EREMOTEIO", doc: "Remote I/O error"},
	info{id: 122, name: "EDQUOT", doc: "Quota exceeded"},
}
