name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '0 6 * * 1' # weekly (every monday at 6 am UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.19'
          check-latest: true
      - name: install deps
        run: |
          go install golang.org/x/lint/golint@latest
      - run: go build -v ./...
      - run: go test -v ./...
      - run: go vet ./...
      - run: golint -set_exit_status ./...
